package com.qac.platform.model;

import com.qac.platform.model.base.BaseTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	public static final Test dao = new Test().dao();
}
