package com.qac.common.model;

import com.qac.common.model.base.BaseAffichecontent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Affichecontent extends BaseAffichecontent<Affichecontent> {
	public static final Affichecontent dao = new Affichecontent().dao();
}
