package com.qac.common.model;

import com.qac.common.model.base.BaseAffichecategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Affichecategory extends BaseAffichecategory<Affichecategory> {
	public static final Affichecategory dao = new Affichecategory().dao();
}
